create table payment_methods (
id integer generated by default as identity,
name varchar(60) not null,
primary key (id));

create table group_permissions (
group_id integer not null,
permission_id integer not null);

create table group_users (
group_id integer not null,
user_id uuid not null);

create table groups (
id integer generated by default as identity,
name varchar(60) not null,
primary key (id));

create table permissions (
id integer generated by default as identity,
description varchar(60),
name varchar(100) not null,
primary key (id));

create table restaurants (
address_city_id integer,
delivery_fee numeric(38,2) not null,
date_created timestamp not null,
date_updated timestamp not null,
id uuid not null default gen_random_uuid(),
kitchen_id uuid not null default gen_random_uuid(),
address_complement varchar(100),
address_neighborhood varchar(100),
address_number varchar(60),
address_street varchar(100),
address_zipcode varchar(60),
name varchar(100) not null,
primary key (id));

create table products (
active boolean not null,
id integer generated by default as identity,
price numeric(38,2) not null,
restaurant_id uuid not null default gen_random_uuid(),
description varchar(100) not null,
name varchar(60) not null,
primary key (id));

create table restaurant_payment_methods (
payment_method_id integer not null,
restaurant_id uuid not null default gen_random_uuid());


create table users (
date_created timestamp not null,
date_updated timestamp not null,
id uuid not null default gen_random_uuid(),
email varchar(80) not null,
name varchar(80) not null,
password varchar(80) not null,
primary key (id));


alter table if exists group_permissions add constraint fk_group_permission_permission
foreign key (permission_id) references permissions;

alter table if exists group_permissions add constraint fk_group_permission_groups
foreign key (group_id) references groups;

alter table if exists group_users add constraint fk_group_users_users
foreign key (user_id) references users;

alter table if exists group_users add constraint fk_group_users_groups
foreign key (group_id) references groups;

alter table if exists products add constraint fk_products_restaurants
foreign key (restaurant_id) references restaurants;

alter table if exists restaurant_payment_methods add constraint fk_restaurant_payment_methods
foreign key (payment_method_id) references payment_methods;

alter table if exists restaurant_payment_methods add constraint fk_restaurant_payments_restaurants
foreign key (restaurant_id) references restaurants;

alter table if exists restaurants add constraint fk_resrautants_cities
foreign key (address_city_id) references cities;

alter table if exists restaurants add constraint fk_restaurants_kitchens
foreign key (kitchen_id) references kitchens;